cache_ttl: '600'
challenge_categories: "\u2600\uFE0F denn\xED v\xFDzva,\U0001F917 lidsk\xE1 interakce,\U0001F499\
  \ zlep\u0161en\xED sv\u011Bta,\U0001F463 dobrodru\u017Estv\xED,\U0001F3CB\uFE0F\
  \ fyzick\xE9 p\u0159ekon\xE1n\xED,\U0001F4DD reportov\xE1n\xED,\U0001F9D8 nitrozpyt"
feed_page_size: '5'
file_system: local
fs_bucket: xchallengecz
link_color: '#002676'
map_embed_url: https://www.google.com/maps/d/u/0/embed?mid=1wwRQybMyy3iPT8M3ub0u3_jzWmpcHpk&ehbc=2E312F
product_id: '9861'
xchallenge_year: '2023'
